services:
  gateway:
    build: .
    environment:
      - PORT=4000
      - INTERNAL_PORT=4001
      - APOLLO_KEY
      - APOLLO_GRAPH_REF
    ports:
      - 4000:4000
      - 4001:4001
      - 9090:9090
  subgraph_one:
    build:
      context: .
      dockerfile: Dockerfile.subgraph
      args:
        - BUILD_CONTEXT=example/subgraphs/one
    environment:
      - PORT=6001
  subgraph_two:
    build:
      context: .
      dockerfile: Dockerfile.subgraph
      args:
        - BUILD_CONTEXT=example/subgraphs/two
    environment:
      - PORT=6002
