FROM --platform=linux/amd64 node:18
ARG BUILD_CONTEXT

WORKDIR /root
COPY package.json yarn.lock .

WORKDIR /root/packages/app
COPY $BUILD_CONTEXT/package.json .
RUN yarn install

COPY $BUILD_CONTEXT/schema.graphql .
COPY $BUILD_CONTEXT/index.js .

CMD ["node", "index.js"]
